---
name: ksnakeduel
version: 17.08.1
summary: Tron-like Game
description: KSnakeDuel is a simple Tron-Clone. You can play KSnakeDuel against the
    computer or a friend. The aim of the game is to live longer than your opponent.
    To do that, avoid running into a wall, your own tail and that of your opponent.
confinement: strict
grade: stable
apps:
    ksnakeduel:
        command: kf5-launch ksnakeduel
        plugs:
        - kde-frameworks-5-plug
        - home
        - x11
        - opengl
        - network
        - network-bind
        - unity7
        - pulseaudio
slots:
    session-dbus-interface:
        interface: dbus
        name: org.kde.ksnakeduel
        bus: session
plugs:
    kde-frameworks-5-plug:
        content: kde-frameworks-5-all
        interface: content
        default-provider: kde-frameworks-5
        target: kf5
parts:
    ksnakeduel:
        after:
        - kde-frameworks-5-dev
        - kde-frameworks-5-env
        plugin: cmake
        build-packages:
        - libkf5kdegames-dev
        - libpulse0
        source: https://download.kde.org/stable/applications/17.08.1/src/ksnakeduel-17.08.1.tar.xz
        configflags:
        - "-DKDE_INSTALL_USE_QT_SYS_PATHS=ON"
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DENABLE_TESTING=OFF"
        - "-DBUILD_TESTING=OFF"
        - "-DKDE_SKIP_TEST_SETTINGS=ON"
