../icons/kdesnake-16.xpm /usr/share/pixmaps
../icons/kdesnake.xpm /usr/share/pixmaps
../icons/ktron-16.xpm /usr/share/pixmaps
../icons/ktron.xpm /usr/share/pixmaps
usr/games/kdesnake
usr/games/ksnakeduel
usr/share/applications/kde4/ksnakeduel.desktop
usr/share/applications/kde4/kdesnake.desktop
usr/share/doc/kde/HTML/en/ktron/common
usr/share/doc/kde/HTML/en/ktron/index.cache.bz2
usr/share/doc/kde/HTML/en/ktron/index.docbook
usr/share/doc/kde/HTML/en/ktron/settings-general.png
usr/share/doc/kde/HTML/en/ktron/settings-theme.png
usr/share/icons/hicolor/128x128/apps/kdesnake.png
usr/share/icons/hicolor/128x128/apps/ktron.png
usr/share/icons/hicolor/16x16/apps/kdesnake.png
usr/share/icons/hicolor/16x16/apps/ktron.png
usr/share/icons/hicolor/22x22/apps/kdesnake.png
usr/share/icons/hicolor/22x22/apps/ktron.png
usr/share/icons/hicolor/256x256/apps/kdesnake.png
usr/share/icons/hicolor/32x32/apps/kdesnake.png
usr/share/icons/hicolor/32x32/apps/ktron.png
usr/share/icons/hicolor/48x48/apps/kdesnake.png
usr/share/icons/hicolor/48x48/apps/ktron.png
usr/share/icons/hicolor/64x64/apps/kdesnake.png
usr/share/icons/hicolor/64x64/apps/ktron.png
usr/share/kde4/apps/ktron/ktronui.rc
usr/share/kde4/apps/ktron/themes/default.desktop
usr/share/kde4/apps/ktron/themes/default.png
usr/share/kde4/apps/ktron/themes/default.svgz
usr/share/kde4/apps/ktron/themes/neon.desktop
usr/share/kde4/apps/ktron/themes/neon.png
usr/share/kde4/apps/ktron/themes/neon.svg
usr/share/kde4/config.kcfg/ktron.kcfg
usr/share/kde4/config/ktron.knsrc
